server:
  port: 8443
  ssl:
    key-store: tomcat.p12
    key-store-type: JKS
    key-alias: tomcat
    key-store-password: tsinghua

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

http:
  port: 8080
